import {fireEvent, render, screen, waitFor} from '@testing-library/react';
import {beforeEach, expect, it, vi} from 'vitest';
import {readerFixture} from '@/features/weekly-reader/test-fixture';
import {getMessages} from '@/i18n/messages';
import {OfflineContentPage} from './OfflineContentPage';
const store = vi.hoisted(() => ({supportsOfflineReader: () => true, getOfflineIdentity: vi.fn(), listOfflineSaves: vi.fn(), readOfflineSave: vi.fn(), removeOfflineSave: vi.fn(), hasPendingReaderWrites: vi.fn().mockResolvedValue(false)}));
vi.mock('@/features/weekly-reader/offline-store', () => store);
vi.mock('@/features/weekly-reader/offline-session', () => ({watchOfflineAccount: () => () => {}}));
vi.mock('@/components/layout/AccountControl', () => ({useAccountIdentity: () => null}));
beforeEach(() => {vi.stubEnv('NEXT_PUBLIC_WEEKLY_READER_ENABLED', 'true'); store.getOfflineIdentity.mockResolvedValue({accountId: 'account-a', epoch: 1}); store.listOfflineSaves.mockResolvedValue([{selector: {accountId: 'account-a', issueNumber: 1739, series: 'general', contentLocale: 'zh-Hant'}, value: readerFixture(), size: 1024}]); store.readOfflineSave.mockResolvedValue({status: 'expired'}); store.removeOfflineSave.mockResolvedValue(undefined);});
it('lists only the saved account with expiry and a reconnect state, without rendering private body text', async () => {
  render(<OfflineContentPage locale="en" messages={getMessages('en').weeklyReader}/>);
  const link = await screen.findByRole('link', {name: /1739 · General bulletin/});
  expect(link).toHaveAttribute('href', '/en/literature-ministry/1739/read/general/zh-Hant');
  expect(screen.getByText('Reconnect to validate this saved bulletin.')).toBeInTheDocument();
  expect(screen.queryByText('Private weekly')).not.toBeInTheDocument();
  vi.spyOn(window, 'confirm').mockReturnValue(true);
  fireEvent.click(screen.getByRole('button', {name: 'Remove download'}));
  await waitFor(() => expect(store.removeOfflineSave).toHaveBeenCalled());
});
