import {fireEvent, render, screen, waitFor} from '@testing-library/react';
import {beforeEach, expect, it, vi} from 'vitest';
import {getMessages} from '@/i18n/messages';
import {readerFixture} from '@/features/weekly-reader/test-fixture';
import {ReaderRecovery} from './ReaderRecovery';
const value = readerFixture();
const mocks = vi.hoisted(() => ({prepare: vi.fn(), finish: vi.fn(), choose: vi.fn(), read: vi.fn(), identity: vi.fn()}));
vi.mock('@/features/weekly-reader/upgrade', () => ({prepareReaderUpgrade: mocks.prepare, finishReaderUpgrade: mocks.finish}));
vi.mock('@/features/weekly-reader/offline-store', () => ({supportsOfflineReader: () => true, getOfflineIdentity: mocks.identity, readOfflineSave: mocks.read, chooseReaderRecovery: mocks.choose}));
const api = {open: vi.fn(), renew: vi.fn(), current: vi.fn(), privateState: vi.fn(), mutate: vi.fn()};
const props = {api, value, selector: {accountId: 'account-a', issueNumber: 1739, series: 'general' as const, contentLocale: 'zh-Hant' as const}, messages: getMessages('en').weeklyReader, onUpdated: vi.fn(), onFailure: vi.fn()};
const cloud = {accountId: 'account-a', documentId: value.document.documentId, appliedRevision: 2, currentRevision: 2, notes: [], highlights: [], progress: null, conflicts: []};
beforeEach(() => {
  vi.resetAllMocks();
  mocks.identity.mockResolvedValue({accountId: 'account-a', epoch: 1}); mocks.read.mockResolvedValue({status: 'available'});
  mocks.prepare.mockResolvedValue({value, state: cloud, queue: [], mutations: [], recovery: [], previousRevision: 1}); mocks.finish.mockResolvedValue(value);
});
it('requires explicit acceptance before switching and retains the reader on cancellation or failure', async () => {
  render(<ReaderRecovery {...props}/>);
  fireEvent.click(screen.getByRole('button', {name: 'Review synchronization'}));
  await screen.findByRole('button', {name: 'Apply and synchronize'});
  expect(mocks.finish).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', {name: 'Keep reading'}));
  expect(props.onUpdated).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', {name: 'Review synchronization'}));
  mocks.finish.mockRejectedValueOnce(new TypeError('offline'));
  fireEvent.click(await screen.findByRole('button', {name: 'Apply and synchronize'}));
  await waitFor(() => expect(props.onFailure).toHaveBeenCalled());
  expect(props.onUpdated).not.toHaveBeenCalled();
});

it('does not lose an unsaved action on revision update and confirms its original ID before manual recovery', async () => {
  mocks.read.mockResolvedValue(null);
  const current = {...value, document: {...value.document, revision: 2}};
  api.current.mockResolvedValue(current); api.privateState.mockResolvedValue({state: cloud});
  const pending = {mutationId: 'original', createdAt: new Date().toISOString(), documentRevision: 1, kind: 'createNote' as const, payload: {noteId: 'note-original', sentenceIds: ['s0'], text: 'Keep my private draft'}};
  const onPendingChange = vi.fn();
  api.mutate.mockImplementation(async (_selector, _value, mutations) => ({state: cloud, results: [{mutationId: mutations[0].mutationId, status: mutations[0].mutationId === 'original' ? 'revision_changed' : 'applied', revision: 2}]}));
  render(<ReaderRecovery {...props} pendingMutation={pending} onPendingChange={onPendingChange}/>);
  fireEvent.click(screen.getByRole('button', {name: 'Review synchronization'}));
  fireEvent.click(await screen.findByRole('button', {name: 'Confirm and retry'}));
  expect(api.mutate.mock.calls[0][2][0]).toEqual(pending);
  expect(await screen.findByRole('textbox', {name: 'Note'})).toHaveValue('Keep my private draft');
  expect(screen.queryByRole('button', {name: 'Apply and synchronize'})).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', {name: 'Keep local'}));
  await screen.findByRole('button', {name: 'Apply and synchronize'});
  expect(api.mutate.mock.calls[1][2][0].mutationId).not.toBe('original');
  expect(api.mutate.mock.calls[1][2][0].payload.text).toBe(pending.payload.text);
  expect(onPendingChange).toHaveBeenLastCalledWith(null);
});
it('shows local and cloud note text and records an explicit cloud choice without discarding on cancel', async () => {
  const mutation = {mutationId: 'old', documentRevision: 1, createdAt: '', kind: 'editNote', baseVersion: 1, payload: {noteId: 'note', text: 'Local text'}};
  mocks.prepare.mockResolvedValue({value, state: {...cloud, notes: [{id: 'note', text: 'Cloud text', version: 2, sentenceIds: ['s0'], deleted: false}]}, queue: [{mutation, sent: true, result: {status: 'note_conflict'}}], mutations: [], recovery: [{mutationId: 'old', reason: 'note_conflict'}], previousRevision: 1});
  render(<ReaderRecovery {...props}/>);
  fireEvent.click(screen.getByRole('button', {name: 'Review synchronization'}));
  expect(await screen.findByDisplayValue('Local text')).toBeInTheDocument();
  expect(screen.getByText('Cloud text')).toBeInTheDocument();
  expect(screen.queryByRole('button', {name: 'Apply and synchronize'})).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', {name: 'Keep cloud'}));
  await waitFor(() => expect(mocks.choose).toHaveBeenCalledWith(props.selector, 'old', null, 1, expect.any(Array)));
});
it('keeps the authorized original quote visible when its sentence was removed', async () => {
  const mutation = {mutationId: 'removed', documentRevision: 1, createdAt: '', kind: 'createNote', payload: {noteId: 'note', sentenceIds: ['s0'], text: 'My draft'}};
  const current = {...value, document: {...value.document, content: {...value.document.content, components: []}, revision: 2}};
  mocks.prepare.mockResolvedValue({value: current, state: cloud, queue: [{mutation, sent: true}], mutations: [], recovery: [{mutationId: 'removed', reason: 'removed_anchor'}], previousRevision: 1});
  render(<ReaderRecovery {...props}/>);
  fireEvent.click(screen.getByRole('button', {name: 'Review synchronization'}));
  expect(await screen.findByText('內容0。')).toBeInTheDocument();
  expect(screen.getByDisplayValue('My draft')).toBeInTheDocument();
});
it('resolves a cloud color conflict without replacing a pending private note', async () => {
  mocks.read.mockResolvedValue(null);
  api.current.mockResolvedValue({...value, document: {...value.document, revision: 2}});
  const conflict = {id: 'color-conflict', sources: [{sentenceId: 's0', color: 'red', quote: 'Original quote'}]};
  let resolved = false;
  api.privateState.mockImplementation(async () => ({state: {...cloud, conflicts: resolved ? [] : [conflict]}}));
  const pending = {mutationId: 'pending-note', createdAt: new Date().toISOString(), documentRevision: 1, kind: 'createNote' as const, payload: {noteId: 'note-a', sentenceIds: ['s0'], text: 'Keep this note'}};
  const onPendingChange = vi.fn();
  api.mutate.mockImplementation(async (_selector, _value, mutations) => {
    const mutation = mutations[0];
    if (mutation.kind === 'resolveHighlightMigrationConflict') resolved = true;
    return {state: cloud, results: [{mutationId: mutation.mutationId, status: resolved ? 'applied' : 'revision_changed', revision: 2}]};
  });
  render(<ReaderRecovery {...props} pendingMutation={pending} onPendingChange={onPendingChange}/>);
  fireEvent.click(screen.getByRole('button', {name: 'Review synchronization'}));
  fireEvent.click(await screen.findByRole('button', {name: 'Confirm and retry'}));
  fireEvent.click(await screen.findByRole('button', {name: props.messages.yellowHighlight}));
  expect(await screen.findByDisplayValue('Keep this note')).toBeInTheDocument();
  expect(onPendingChange).not.toHaveBeenCalled();
  expect(api.mutate.mock.calls[0][2][0]).toEqual(pending);
  expect(api.mutate.mock.calls[1][2][0].kind).toBe('resolveHighlightMigrationConflict');
});
