/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bulletins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicBulletins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulletins/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestPublicBulletin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bulletins/{issueDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicBulletinByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminBulletins"];
        put?: never;
        post: operations["createBulletinIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminBulletin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["putBulletinVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/upload-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBulletinUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/assets/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeBulletinUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishBulletin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bulletins/{issueId}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unpublishBulletin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @default zh-Hant
         * @enum {string}
         */
        Locale: "zh-Hant" | "zh-Hans" | "en";
        /** @enum {string} */
        BulletinStatus: "draft" | "publishing" | "published" | "unpublished" | "archived";
        /** @enum {string} */
        BulletinVersionStatus: "draft" | "publishing" | "published" | "unpublished";
        PageMeta: {
            page: number;
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        BulletinVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            issueId: string;
            locale: components["schemas"]["Locale"];
            title: string;
            pdfAssetId: string;
            pdfFileName: string;
            publicGrantId?: string;
            status: components["schemas"]["BulletinVersionStatus"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BulletinIssue: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            issueDate: string;
            status: components["schemas"]["BulletinStatus"];
            /** Format: int64 */
            version: number;
            createdBy: string;
            updatedBy: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            versions: components["schemas"]["BulletinVersion"][];
        };
        PublicBulletin: {
            /** Format: date */
            issueDate: string;
            locale: components["schemas"]["Locale"];
            title: string;
            downloadUrl: string;
            /** Format: date-time */
            publishedAt: string;
            /** Format: int64 */
            version: number;
        };
        Workflow: {
            /** Format: uuid */
            id: string;
            status: string;
            /** Format: int64 */
            aggregateVersion: number;
            /** Format: date-time */
            createdAt: string;
        };
        AssetSummary: {
            id: string;
        };
        UploadTarget: {
            /** Format: uri */
            url: string;
            method: string;
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        CreatedUpload: {
            asset: components["schemas"]["AssetSummary"];
            uploadTarget: components["schemas"]["UploadTarget"];
        };
        CreateBulletinInput: {
            /** Format: date */
            issueDate: string;
        };
        CreateBulletinUploadInput: {
            locale: components["schemas"]["Locale"];
            fileName: string;
            /** @constant */
            mimeType: "application/pdf";
            /** Format: int64 */
            sizeBytes: number;
        };
        PutBulletinVersionInput: {
            locale: components["schemas"]["Locale"];
            title: string;
            pdfAssetId: string;
            pdfFileName: string;
        };
        CompleteBulletinUploadInput: {
            locale: components["schemas"]["Locale"];
            title: string;
            fileName: string;
            /** @constant */
            mimeType: "application/pdf";
            /** Format: int64 */
            sizeBytes: number;
            checksumSha256: string;
        };
        PublicationInput: {
            locale: components["schemas"]["Locale"];
        };
        BulletinIssueEnvelope: {
            data: components["schemas"]["BulletinIssue"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        BulletinListEnvelope: {
            data: components["schemas"]["BulletinIssue"][];
            meta: components["schemas"]["PageMeta"];
            error?: null;
        };
        PublicBulletinEnvelope: {
            data: components["schemas"]["PublicBulletin"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        PublicBulletinListEnvelope: {
            data: components["schemas"]["PublicBulletin"][];
            meta: components["schemas"]["PageMeta"];
            error?: null;
        };
        CreatedUploadEnvelope: {
            data: components["schemas"]["CreatedUpload"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        WorkflowEnvelope: {
            data: components["schemas"]["Workflow"];
            meta: {
                [key: string]: unknown;
            };
            error?: null;
        };
        ErrorEnvelope: {
            data: null;
            meta: {
                [key: string]: unknown;
            };
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description Bulletin issue */
        BulletinIssue: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BulletinIssueEnvelope"];
            };
        };
        /** @description Published bulletin */
        PublicBulletin: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PublicBulletinEnvelope"];
            };
        };
        /** @description Standard API error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Locale: components["schemas"]["Locale"];
        Page: number;
        PageSize: number;
        IssueID: string;
        IdempotencyKey: string;
        IfMatch: string;
    };
    requestBodies: {
        PublicationInput: {
            content: {
                "application/json": components["schemas"]["PublicationInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPublicBulletins: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published bulletin page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBulletinListEnvelope"];
                };
            };
        };
    };
    getLatestPublicBulletin: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicBulletin"];
            404: components["responses"]["Error"];
        };
    };
    getPublicBulletinByDate: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                issueDate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PublicBulletin"];
            404: components["responses"]["Error"];
        };
    };
    listAdminBulletins: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["BulletinStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CMS bulletin list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulletinListEnvelope"];
                };
            };
        };
    };
    createBulletinIssue: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBulletinInput"];
            };
        };
        responses: {
            201: components["responses"]["BulletinIssue"];
            409: components["responses"]["Error"];
        };
    };
    getAdminBulletin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BulletinIssue"];
            404: components["responses"]["Error"];
        };
    };
    putBulletinVersion: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutBulletinVersionInput"];
            };
        };
        responses: {
            200: components["responses"]["BulletinIssue"];
            412: components["responses"]["Error"];
        };
    };
    createBulletinUploadSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBulletinUploadInput"];
            };
        };
        responses: {
            /** @description Short-lived asset upload target created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUploadEnvelope"];
                };
            };
        };
    };
    completeBulletinUpload: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteBulletinUploadInput"];
            };
        };
        responses: {
            200: components["responses"]["BulletinIssue"];
            412: components["responses"]["Error"];
        };
    };
    publishBulletin: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PublicationInput"];
        responses: {
            /** @description Publication workflow accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    unpublishBulletin: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                issueId: components["parameters"]["IssueID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PublicationInput"];
        responses: {
            200: components["responses"]["BulletinIssue"];
            412: components["responses"]["Error"];
        };
    };
}
